

export type Product = {
  id: string;
  title: string;
  media: string;
  author: string;
  price: string;
  sales: number;
  rating: number;
  link: string;
  link2: string;
  splineLink?: string;
  badge?:boolean;
};

export const coffeeData: {
  hotDrinks: Product[];
  coldDrinks: Product[];
  frappe: Product[];
  soda:Product[];
  pastries: Product[];
} = {
  hotDrinks: [
    {
      id: '1',
      title: 'Hot Americano',
      media: '/images/9.png',
      author: 'Strong and bold, perfect for a quick caffeine hit.',
      price: '₱89',
      sales: 12,
      rating: 4,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
      
    },
    {
      id: '2',
      title: 'Hot Cappuccino',
      media: '/images/7.png',
      author: 'A classic blend of espresso, steamed milk, and foam.',
      price: '₱129',
      sales: 18,
      rating: 5,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
      
    },
    {
      id: '3',
      title: 'Hot Spanish Latte',
      media: '/images/8.png',
      author: 'Sweetened milk and espresso for a smooth, rich taste.',
      price: '₱129',
      sales: 9,
      rating: 4,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
    {
      id: '4',
      title: 'Hot Mocha Latte',
      media: '/images/6.png',
      author: 'A delicious mix of coffee and rich chocolate.',
      price: '₱129',
      sales: 15,
      rating: 4,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
    {
      id: '5',
      title: 'Hot Caramel Macchiato',
      media: '/images/10.png',
      author: 'Espresso with vanilla, milk, and a caramel drizzle.',
      price: '₱139',
      sales: 7,
      rating: 5,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
    {
      id: '6',
      title: 'Hot Cafe Latte',
      media: '/images/11.png',
      author: 'Smooth and creamy with a mellow espresso base.',
      price: '₱129',
      sales: 14,
      rating: 4,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
    {
      id: '7',
      title: 'Hot Matcha Latte',
      media: '/images/29.png',
      author: 'Earthy matcha with steamed milk for a zen experience.',
      price: '₱139',
      sales: 6,
      rating: 4,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
    {
      id: '8',
      title: 'Hot Belagio',
      media: '/images/30.png',
      author: 'A rich European-style hot chocolate drink.',
      price: '₱129',
      sales: 11,
      rating: 5,
      link: 'https://elements.envato.com/photos/blanket',
      link2: '/Contact',
    },
  ],

  coldDrinks: [
  {
    id: '9',
    title: 'Cold Americano',
    media: '/images/12.png',
    author: 'Strong and bold, served cold for a refreshing kick.',
    price: '₱89',
    sales: 14,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '10',
    title: 'Cold Mocha Latte',
    media: '/images/13.png',
    author: 'Smooth blend of espresso, chocolate, and milk.',
    price: '₱129',
    sales: 19,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '11',
    title: 'Cold Spanish Latte',
    media: '/images/14.png',
    author: 'A creamy and sweet latte with a Spanish twist.',
    price: '₱139',
    sales: 9,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '12',
    title: 'Cold Matcha Caramel',
    media: '/images/15.png',
    author: 'Earthy matcha meets sweet, rich caramel.',
    price: '₱139',
    sales: 11,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '13',
    title: 'Cold Caramel Macchiato',
    media: '/images/16.png',
    author: 'Creamy layers of espresso and caramel.',
    price: '₱139',
    sales: 17,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '14',
    title: 'Cold Strawberry Matcha',
    media: '/images/17.png',
    author: 'Fresh strawberries and smooth matcha fusion.',
    price: '₱139',
    sales: 7,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
],


 frappe: [
  {
    id: '15',
    title: 'Mocha Frappe',
    media: '/images/18.png',
    author: 'Chocolatey and icy mocha goodness in every sip.',
    price: '₱139',
    sales: 13,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '16',
    title: 'Matcha Frappe',
    media: '/images/19.png',
    author: 'Icy green tea delight, creamy and energizing.',
    price: '₱139',
    sales: 18,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '17',
    title: 'Mocha Crumble Frappe',
    media: '/images/20.png',
    author: 'Blended mocha with crunchy chocolate crumbles.',
    price: '₱139',
    sales: 7,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '18',
    title: 'Cookies and Cream',
    media: '/images/21.png',
    author: 'Classic cookies blended into creamy perfection.',
    price: '₱129',
    sales: 16,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '19',
    title: 'Double Chocolate',
    media: '/images/22.png',
    author: 'Chocolate overload with double the sweetness.',
    price: '₱129',
    sales: 10,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '20',
    title: 'Salted Caramel',
    media: '/images/23.png',
    author: 'Sweet caramel with a pinch of sea salt.',
    price: '₱129',
    sales: 20,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '21',
    title: 'Strawberry Frappe',
    media: '/images/24.png',
    author: 'Creamy strawberry treat, chilled to perfection.',
    price: '₱139',
    sales: 8,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '22',
    title: 'Coffee Frappe (Classic)',
    media: '/images/31.png',
    author: 'Classic blended coffee, rich and smooth.',
    price: '₱129',
    sales: 15,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
],
soda: [
  {
    id: '23',
    title: 'Passion Fruit Soda',
    media: '/images/26.png',
    author: 'Tropical and zesty, perfect for a hot day.',
    price: '₱79',
    sales: 11,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '24',
    title: 'Strawberry Soda',
    media: '/images/27.png',
    author: 'Sweet strawberry fizz with a cool kick.',
    price: '₱79',
    sales: 14,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '25',
    title: 'Green Apple Soda',
    media: '/images/28.png',
    author: 'Crisp green apple flavor with sparkling fun.',
    price: '₱79',
    sales: 9,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
  },
  {
    id: '26',
    title: 'Lychee Soda',
    media: '/images/26.png',
    author: 'Floral and refreshing with light lychee taste.',
    price: '₱79',
    sales: 6,
    rating: 4,
    link: 'https://elements.envato.com/photos/blanket',
    link2: '/checkout',
    badge:true,
  },
],

pastries: [
    {
      id: '27',
      title: 'Brownies',
      media: '/images/32.png',
      author: 'Classic fudgy brownies, rich and chewy.',
      price: '₱45',
      sales: 22,
      rating: 5,
      link: '#',
      link2: '/checkout',
    },
    {
      id: '28',
      title: 'Revel Bars',
      media: '/images/33.png',
      author: 'Chewy oat bars layered with rich chocolate.',
      price: '₱45',
      sales: 18,
      rating: 4,
      link: '#',
      link2: '/checkout',
    },
    {
      id: '29',
      title: 'S’mores Cookies',
      media: '/images/34.png',
      author: 'Graham, chocolate, and marshmallow in one cookie.',
      price: '₱50',
      sales: 20,
      rating: 5,
      link: '#',
      link2: '/checkout',
    },
    {
      id: '30',
      title: 'Marbled Chocolate Creamcheese Cookies',
      media: '/images/35.png',
      author: 'A mix of white and dark chocolate swirls.',
      price: '₱50',
      sales: 17,
      rating: 4,
      link: '#',
      link2: '/checkout',
    },
    {
      id: '31',
      title: 'NYC Cookies',
      media: '/images/35.png',
      author: 'Thick, chunky cookies inspired by New York bakeries.',
      price: '₱50',
      sales: 25,
      rating: 5,
      link: '#',
      link2: '/checkout',
      badge:true,
    },
  ],


};
